parameters:

    featureTypes:

        polyTestFeature: &polyTestFeature
           connection: search_db
           table: polygons
           uniqueId: gid
           geomType: polygon
           geomField: geom
           srid: 4326

        ausstattung:
            connection: digi
            table: verkehr.ausstattung
            uniqueId: ausst_id
            geomType: point
            geomField: the_geom
            srid: 31466
            #fields: [ausst_id,ausst_bem,ausst_jahr]

        ausstattung2:
            connection: digi
            table: verkehr.ausstattung
            uniqueId: oid
            geomType: polygon
            geomField: the_geom
            srid: 31466
            fields: [ausst_bem,ausst_jahr]

        hauses:
            connection: digi
            table: verkehr.ausstattung
            uniqueId: ausst_id
            geomType: point
            geomField: the_geom
            srid: 31466
            filter: ausst_zustand = 2
            uploadPath: /data/wesseling/

    schemes:
        polygoneScheme: &polygoneScheme
           label: Polygons
           maxResults: 1500
           featureType: *polyTestFeature
           openFormAfterEdit: true
           allowDelete: true

           # Features Digitalisieren auf der Karte (Verändern und Erstellen)
           # Default: true
           allowDigitize: true

           # Formular Daten Änderungen
           # Default: true
           allowEditData: true

           # Den Layer dauerhaft anzeigen.
           # Oder nur wenn explicit über Select gewählt und nur wenn active ist
           # Default: false
           displayPermanent: true

           # Layer Features erst wenn das Element active ist und Schema selectiert ist zeigen.
           # Wenn auf "false" ist und Schema active ist, werden die Features, obwohl der Element selbst
           # nicht active ist troztdem angezeigt.
           # Default: true
           displayIfActive: true

           # Tool set
           toolset:
               - type: drawRectangle
               - type: drawCircle
               - type: drawEllipse
               - type: drawDonut
               - type: modifyFeature
               - type: moveFeature
               - type: selectFeature
               - type: removeSelected

           popup:
               title: Polygon test suite
               width: 500px
           tableFields: { gid: { label: Nr., width: 70px}, name: { label: Name } }
           formItems:
               - type: tabs
                 children:
#                       - type: form
#                         title: Test 2a
#                         children:
#
#                             - type: radio
#                               title: Radio Cool Thing
#
#                             - type: breakLine
#                             - type: tabs
#                               children:
#                                   - type: input
#                                     title: Name
#                                     placeholder: Hier nahme eingeben
#                                     css: {width: 50%}
#
#                                   - type: select
#                                     title: anrede
#                                     options: ["Herr", "Fraulein", "Trans"]

                       - type: form
                         title: User profile
                         css: { padding: 10px }
                         children:
                           - type: label
                             title: Welcome to the digitize demo. Try the new Mapbender3 feature!
                           - type: breakLine

                           # Field set
                           # https://trac.wheregroup.com/cp/issues/3929
                           - type: fieldSet
                             children:
#                                - type: select
#                                  name: title
#                                  title: Anrede
#                                  options: [Herr, Frau]
#                                  css: {width: 33%}

                                - type: input
                                  name: firstname
                                  title: Vorname
                                  infoText: Die Vorname
                                  css: {width: 33%}

                                - type: input
                                  name: lastname
                                  title: Nachname
                                  infoText: Die Nachname
                                  css: {width: 33%}

                           - type: breakLine

                           - type: textArea
                             title: Description
                             infoText: Info text

                           - type: textArea
                             infoText: Info text

                           - type: checkbox
                             infoText: Info text
                             title: "Checkbox #1"
                             infoText: Info text

                           - type: radio
                             infoText: Info text
                             title: "Radio #1"
                             infoText: Info text

                           - type: input
                             infoText: Info text

                           - type: select
                             options: [1,2]
                             infoText: Info text

                           - type: select
                             options: [1,2]
                             infoText: Info text
                             title: Noch ein select mit Titel

                           - type: breakLine
                           - type: fieldSet
                             children:
                               - type: textArea
                                 title: Description
                                 infoText: Info text
                                 css: {width: 30%}

                               - type: textArea
                                 infoText: Info text
                                 css: {width: 30%}

                               - type: checkbox
                                 infoText: Info text
                                 title: "Checkbox #1"
                                 infoText: Info text
                                 css: {width: 30%}

                               - type: radio
                                 infoText: Info text
                                 title: "Radio #1"
                                 infoText: Info text
                                 css: {width: 30%}

                               - type: input
                                 infoText: Info text
                                 css: {width: 30%}

                               - type: input
                                 title: Bechreibung
                                 infoText: Info text
                                 css: {width: 30%}


                               - type: select
                                 options: [1,2]
                                 css: {width: 30%}
                                 infoText: Info text

                               - type: select
                                 options: [1,2]
                                 infoText: Info text
                                 title: Noch ein select mit Titel

                           - type: breakLine

                           - type: fieldSet
                             children:

                               # Datepicker
                               # https://trac.wheregroup.com/cp/issues/3729
                               - type: date
                                 name: date_favorite
                                 title: Birthdate
                                 placeholder: DD-MM-YYYY
                                 infoText: Info Text

                                 # Datumsformat (optional)
                                 dateFormat: yy-mm-dd
                                 css: {width: 30%}

                               - type: input
                                 name: email
                                 title: E-Mail
                                 css: {width: 70%}
                                 infoText: Info Text

                       - type: form
                         title: Basic information
                         css: { padding: 10px }
                         children:

                             - type: input
                               title: Name
                               name: name
                               mandatoryText: Please give a name to the new object.
                               infoText: You need to give a name to the new object.
                               mandatory: true

                             - type: breakLine

                             - type: select
                               multiple: true
                               name: category
                               infoText: Info Text

                               # array, text, json, serialize
#                               fieldType: text
                               separator: ,
                               options:  ['Prof.','Dr.', 'med.', 'jur.','vet.','habil.']

        lineScheme: &lineScheme
            label: Lines
            maxResults: 1500
            featureType:
                connection: search_db
                table: lines
                uniqueId: gid
                geomType: line
                geomField: geom
                srid: 4326
            openFormAfterEdit: true
            popup:
                title: Line test suite
                width: 500px
            tableFields:
                gid: { label: Nr. }
                name: { label: Name }
            formItems:
                - type: form
                  title: mb.basic.information
                  css: { padding: 10px }
                  children:
                      - type: label
                        title: trans:mb.digitizer.feature.edit
                      - type: input
                        title: Name
                        mandatory: true
                        name: name
                        mandatoryText: mb.digitizer.fiel.object.name
                        infoText: Help: Please give a name to the new object.
                      - type: select
                        title: Type
                        name: type
                        options: { A: A, B: B, C: C, D: D, E: E }

        poiScheme: &poiScheme
            label: POI
            maxResults: 1500
            allowDelete: false
            featureType:
                connection: search_db
                table: poi
                uniqueId: gid
                geomType: point
                geomField: geom
                srid: 4326
            openFormAfterEdit: true
            # Tool set
    #        toolset:
    #            - type: drawPoint
    #            - type: moveFeature
    #            - type: selectFeature
    #            - type: removeSelected
            popup:
                title: POI Test Suite
                width: 500px
            tableFields: {gid: {label: Nr.}, name: {label: Name}}
            formItems:
               - type: form
                 css: {padding: 10px}
                 children:
                     - type: select
                       title: Type
                       name: type
                       options: {A:A, B:B, C:C, D:D, E:E}
                     - type: input
                       title: Name
                       mandatory: true
                       name: name
                       mandatoryText: Please give a name to the poi.
                     - type: breakLine
                     - type: fieldSet
                       children:
                           - type: date
                             title: favorite Date
                             name: date_favorite
                             mandatory: true
                             dateFormat: yy-mm-dd
                             css: {width: 25%}
                     - type: breakLine
                     - type: fieldSet
                       children:
                           - type: input
                             title: Firstname
                             name: firstname
                             css: {width: 30%}
                           - type: input
                             title: Lastname
                             name: lastname
                             css: {width: 30%}
                           - type: input
                             title: E-Mail
                             name: email
                             css: {width: 40%}
    layerSets:
        osm_overview: &osm_overview
            class: Mapbender\WmsBundle\Entity\WmsInstance
            title: OSM Demo
            url: http://osm-demo.wheregroup.com/service
            layers:
                30: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: true }
            info_format: text/html
            visible: true
            format: image/png
            transparent: true
            tiled: true
            opacity: 100

    applications:
        digitest:
            title: Digitalizer Test
            description: Digitalisierung Testumgebung
            published: true
            initializeOnStart: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            regionProperties:
                - name: sidepane
                  properties: {"name": "accordion", "label": "mb.manager.template.region.accordion.label"}
            layersets:
                main:
                    osm: *osm_overview
            elements:
                sidepane:
                    digitizer:
                        class: Mapbender\DigitizerBundle\Element\Digitizer
                        title: Digitalisierung
                        target: map

                        # Shows DB errors as notify message directly
                        debug: true

                        # Loads JS files from "web" path.
                        # For tests only!
                        jsSrc:
                            - /components/vis-ui.js/src/js/elements/geo.toolset.js
                            - /components/vis-ui.js/src/js/elements/date.selector.js
                            - /components/vis-ui.js/src/js/utils/fn.formData.js
                            - /components/vis-ui.js/src/js/jquery.form.generator.js
                        schemes:
                            polygon: *polygoneScheme
                            line: *lineScheme
#                            poi: *poiScheme
                content:
                    map:
                        title: Main Map
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [main]
                        srs: EPSG:25832
                        units: m
                        extents:
                            start: [361000,5619000,371150,5625000]
                            max: [-500000,4350000,1600000,6850000]
                        scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        maxResolution: auto
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:900913","EPSG:4326"]