parameters:
  applications:
    mapbender_data_source:
        title: &title Mapbender data source test
        description: *title
        published: true
        template:  Mapbender\CoreBundle\Template\Fullscreen
        regionProperties:
          - name: sidepane
            properties:
              name: accordion
              label: mb.manager.template.region.accordion.label
        layersets:
          main:
            osm: &osm_layer
              class: Mapbender\WmsBundle\Entity\WmsInstance
              title: OSM Demo
              url: http://osm-demo.wheregroup.com/service
              layers:
                30: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: true }
              info_format: text/html
              visible: true
              format: image/png
              transparent: true
              tiled: true
              opacity: 100
          overview:
            osm_overview:
              <<: *osm_layer
              tiled: false
        elements:
          toolbar:
            about:
              title: About
              label: true
              class: Mapbender\CoreBundle\Element\AboutDialog
          content:
              map:
                  title: Main Map
                  class: Mapbender\CoreBundle\Element\Map
                  layersets: [main]
                  srs: EPSG:25832
                  units: m
                  extents:
                      start: [361000,5619000,371150,5625000]
                      max: [-500000,4350000,1600000,6850000]
                  scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                  maxResolution: 'auto'
                  otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:900913","EPSG:4326"]
              zoombar:
                  class: Mapbender\CoreBundle\Element\ZoomBar
                  target: map
                  components: ["pan","history","zoom_box","zoom_max","zoom_slider"]
                  position: [15em, 3em]
                  stepsize: 50
                  stepbypixel: true
                  anchor: right-top
                  position: [200,40]
                  draggable: false
          sidepane:
            dataStore:
                title: Data Store
                class: Mapbender\CoreBundle\Element\HTMLElement
                content: >
                  <div style="color: #6FB536; font-weight:bold">DataStore</div>
                classes: html-element-inline
            layertree:
              title: Layertree
              class: Mapbender\CoreBundle\Element\Layertree
              target: map
              type: element
              displaytype: tree
              useAccordion: false
              autoOpen: false
              titlemaxlength: 30
              showBaseSource: true
              layerRemove: true
              menu: [opacity, zoomtolayer, metadata]

          footer:
            activityindicator:
              class: Mapbender\CoreBundle\Element\ActivityIndicator
              title: Activity Indicator
              activityClass: mb-activity
              ajaxActivityClass: mb-activity-ajax
              tileActivityClass: mb-activity-tile
            srs:
              class: Mapbender\CoreBundle\Element\SrsSelector
              title: SRS Selector
              tooltip: SRS Selector
              label: false
              target: map
            scaleselector:
              class: Mapbender\CoreBundle\Element\ScaleSelector
              title: Scale Selector
              tooltip: Scale Selector
              label: false
              target: map
            copyrightButton:
              title: © OpenStreetMap contributors
              class: Mapbender\CoreBundle\Element\Button
              label: true
              click: http://www.openstreetmap.org/copyright