about: Mapbender\AboutBundle\MapbenderAboutBundle
coordinatesdisplay: Mapbender\CoordinatesDisplayBundle\MapbenderCoordinatesDisplayBundle
ol3map: Mapbender\OL3Bundle\MapbenderOL3Bundle
imageexport: Mapbender\ImageexportBundle\MapbenderImageexportBundle
mobile: Mapbender\MobileBundle\MapbenderMobileBundle
#drupalintegration: Mapbender\DrupalIntegrationBundle\MapbenderDrupalIntegrationBundle
kml: Mapbender\KmlBundle\MapbenderKmlBundle
srsselector: Mapbender\SrsSelectorBundle\MapbenderSrsSelectorBundle
zoomcoordinate: Mapbender\ZoomcoordinateBundle\MapbenderZoomcoordinateBundle
