about: Mapbender\AboutBundle\MapbenderAboutBundle
activityindicator: Mapbender\ActivityIndicatorBundle\MapbenderActivityIndicatorBundle
basesourceswitcher: Mapbender\BaseSourceSwitcherBundle\MapbenderBaseSourceSwitcherBundle
coordinatesdisplay: Mapbender\CoordinatesDisplayBundle\MapbenderCoordinatesDisplayBundle
copyright: Mapbender\CopyrightBundle\MapbenderCopyrightBundle
featureinfo: Mapbender\FeatureInfoBundle\MapbenderFeatureInfoBundle
legend: Mapbender\LegendBundle\MapbenderLegendBundle
ol3map: Mapbender\OL3Bundle\MapbenderOL3Bundle
imageexport: Mapbender\ImageexportBundle\MapbenderImageexportBundle
mobile: Mapbender\MobileBundle\MapbenderMobileBundle
#drupalintegration: Mapbender\DrupalIntegrationBundle\MapbenderDrupalIntegrationBundle
kml: Mapbender\KmlBundle\MapbenderKmlBundle
poi: Mapbender\POIBundle\MapbenderPOIBundle
ruler: Mapbender\RulerBundle\MapbenderRulerBundle
srsselector: Mapbender\SrsSelectorBundle\MapbenderSrsSelectorBundle
zoomcoordinate: Mapbender\ZoomcoordinateBundle\MapbenderZoomcoordinateBundle
