imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
parameters:
    pdo.db_options:
        db_table: fom_session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time
        
framework:
    #esi:             ~
    translator:      { fallback: %fallback_locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        cookie_httponly: true
        cookie_secure: %cookie_secure%
        cookie_lifetime: %cookie_lifetime%
        handler_id: session.handler.pdo
    serializer:
        enabled: true

services:
    pdo:
        class: PDO
        arguments:
            - "pgsql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        fom:    %fom%
    form:
        resources:
            - 'FOMCoreBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    ruby: %ruby_path%
    filters:
        cssrewrite: ~
        sass: ~
        compass:
            bin: %compass_path%
            no_line_comments: true
            style: compressed
            load_paths:
                 - "%kernel.root_dir%/../mapbender/src/Mapbender/CoreBundle/Resources/public/sass"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOM Manager Configuration
fom_manager:
    route_prefix: /manager

# FOM User Configuration
fom_user:
    selfregister: false
    reset_password: true
    max_registration_time: 1
    max_reset_time: 1
    mail_from_address: wizard@oz.net
    mail_from_name: Wizard of Oz
    profile_entity: FOM\UserBundle\Entity\BasicProfile
    profile_formtype: FOM\UserBundle\Form\Type\BasicProfileType
    profile_template: FOMUserBundle:User:basic_profile.html.twig
    self_registration_groups:
        - Self Registered
        - Demo Group

# OWSProxy Configuration
ows_proxy3_core:
    logging: true
    obfuscate_client_ip: true
    proxy:
#        host: localhost
#        port: 8888
        connecttimeout: 60
        timeout: 90
#        user: user
#        password: password
#        noproxy:
#            - host_a
#            - host_b

# Mapbender Configuration
mapbender_core:
    sass_assets: false
