services:
  mapbender2_geometryprovider:
    class: OwsProxy3\CoreBundle\GeometryProvider\Mapbender2GeometryProvider
    arguments: [ "@service_container" ]

parameters:
    layerSets:
        mapbenderUsers: &mapbenderUsers
            class: Mapbender\WmsBundle\Entity\WmsInstance
            title: Mapbender Users
            url: http://wms.wheregroup.com/cgi-bin/mapbender_user.xml
            layers:
                10: { name: Mapbender_User,    title : User, visible: true, legendurl: http://wms.wheregroup.com/cgi-bin/mapbender_user.xml?REQUEST=GetLegendGraphic&VERSION=1.1.1&SERVICE=WMS&Layer=Mapbender_User&FORMAT=image/png }
                22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
            info_format: text/html
            visible: true
            format: image/png
            transparent: true
            tiled: true
            opacity: 85

        osm_overview: &osm_overview
            class: Mapbender\WmsBundle\Entity\WmsInstance
            title: OSM Demo
            url: http://osm-demo.wheregroup.com/service
            layers:
                30: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: true }
            info_format: text/html
            visible: true
            format: image/png
            transparent: true
            tiled: true
            opacity: 100
    applications: []
